# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMemasukkanbarangkekeranjang():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_memasukkanbarangkekeranjang(self):
    # Test name: Memasukkan barang ke keranjang
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://shopee.co.id/")
    # 2 | setWindowSize | 1296x696 | 
    self.driver.set_window_size(1296, 696)
    # 3 | runScript | window.scrollTo(0,652) | 
    self.driver.execute_script("window.scrollTo(0,652)")
    # 4 | runScript | window.scrollTo(0,1411.3333740234375) | 
    self.driver.execute_script("window.scrollTo(0,1411.3333740234375)")
    # 5 | runScript | window.scrollTo(0,1819.3333740234375) | 
    self.driver.execute_script("window.scrollTo(0,1819.3333740234375)")
    # 6 | click | css=.Odjj3U:nth-child(2) .shopee_itemcard__promotion_overlay:nth-child(2) > .w-full:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".Odjj3U:nth-child(2) .shopee_itemcard__promotion_overlay:nth-child(2) > .w-full:nth-child(1)").click()
    # 7 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 8 | runScript | window.scrollTo(0,280) | 
    self.driver.execute_script("window.scrollTo(0,280)")
    # 9 | mouseOver | css=.btn--l > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn--l > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | mouseOut | css=.btn--l > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 11 | mouseOver | css=.QA-ylc | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".QA-ylc")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | mouseOut | css=.QA-ylc | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 13 | click | css=.btn--l > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn--l > span").click()
    # 14 | click | css=.hUWqqt:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".hUWqqt:nth-child(2)").click()
    # 15 | click | css=.btn--l > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn--l > span").click()
  
