# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMenginputdataloginyangbenar():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_menginputdataloginyangbenar(self):
    # Test name: Menginput data login yang benar
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://shopee.co.id/")
    # 2 | setWindowSize | 1296x696 | 
    self.driver.set_window_size(1296, 696)
    # 3 | mouseOver | linkText=Log In | 
    element = self.driver.find_element(By.LINK_TEXT, "Log In")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | linkText=Log In | 
    self.driver.find_element(By.LINK_TEXT, "Log In").click()
    # 5 | type | name=loginKey | ev10n9un66
    self.driver.find_element(By.NAME, "loginKey").send_keys("ev10n9un66")
    # 6 | click | name=password | 
    self.driver.find_element(By.NAME, "password").click()
    # 7 | type | name=password | Thismyself9
    self.driver.find_element(By.NAME, "password").send_keys("Thismyself9")
    # 8 | click | css=.wyhvVD | 
    self.driver.find_element(By.CSS_SELECTOR, ".wyhvVD").click()
    # 9 | click | css=.dWxniD | 
    self.driver.find_element(By.CSS_SELECTOR, ".dWxniD").click()
    # 10 | click | css=.GhFPxQ | 
    self.driver.find_element(By.CSS_SELECTOR, ".GhFPxQ").click()
  
