# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMenginputnamabarangdipencarian():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_menginputnamabarangdipencarian(self):
    # Test name: Menginput nama barang di pencarian
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://shopee.co.id/")
    # 2 | setWindowSize | 1296x696 | 
    self.driver.set_window_size(1296, 696)
    # 3 | click | css=.shopee-searchbar-input__input | 
    self.driver.find_element(By.CSS_SELECTOR, ".shopee-searchbar-input__input").click()
    # 4 | type | css=.shopee-searchbar-input__input | piring
    self.driver.find_element(By.CSS_SELECTOR, ".shopee-searchbar-input__input").send_keys("piring")
    # 5 | sendKeys | css=.shopee-searchbar-input__input | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".shopee-searchbar-input__input").send_keys(Keys.ENTER)
    # 6 | runScript | window.scrollTo(0,98) | 
    self.driver.execute_script("window.scrollTo(0,98)")
    # 7 | runScript | window.scrollTo(0,199.3333282470703) | 
    self.driver.execute_script("window.scrollTo(0,199.3333282470703)")
  
