# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMenginputkandengankondisiemailbenardanpasswordsalah():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_menginputkandengankondisiemailbenardanpasswordsalah(self):
    # Test name: Menginputkan dengan kondisi email benar dan password salah
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://shopee.co.id/")
    # 2 | setWindowSize | 1296x696 | 
    self.driver.set_window_size(1296, 696)
    # 3 | click | linkText=Log In | 
    self.driver.find_element(By.LINK_TEXT, "Log In").click()
    # 4 | type | name=loginKey | ev10n9un66
    self.driver.find_element(By.NAME, "loginKey").send_keys("ev10n9un66")
    # 5 | click | name=password | 
    self.driver.find_element(By.NAME, "password").click()
    # 6 | type | name=password | koaeiojdowjojow
    self.driver.find_element(By.NAME, "password").send_keys("koaeiojdowjojow")
    # 7 | click | css=.wyhvVD | 
    self.driver.find_element(By.CSS_SELECTOR, ".wyhvVD").click()
  
