# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPengajuanberkasuntukdataDMSdenganukuranberkas5mb():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pengajuanberkasuntukdataDMSdenganukuranberkas5mb(self):
    # Test name: Pengajuan berkas untuk data DMS, dengan ukuran berkas >5mb
    # Step # | name | target | value
    # 1 | open | /beranda/beranda/view | 
    self.driver.get("https://simaster.ugm.ac.id/beranda/beranda/view")
    # 2 | setWindowSize | 1296x696 | 
    self.driver.set_window_size(1296, 696)
    # 3 | click | css=.dropdown:nth-child(4) > a > .px-nav-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown:nth-child(4) > a > .px-nav-label").click()
    # 4 | click | css=.open li:nth-child(3) .px-nav-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".open li:nth-child(3) .px-nav-label").click()
    # 5 | click | linkText=Unggah Berkas | 
    self.driver.find_element(By.LINK_TEXT, "Unggah Berkas").click()
    # 6 | click | id=select2-file_semester-container | 
    self.driver.find_element(By.ID, "select2-file_semester-container").click()
    # 7 | click | id=select2-jenis_id-container | 
    self.driver.find_element(By.ID, "select2-jenis_id-container").click()
    # 8 | click | name=file_title | 
    self.driver.find_element(By.NAME, "file_title").click()
    # 9 | type | name=file_title | foto
    self.driver.find_element(By.NAME, "file_title").send_keys("foto")
    # 10 | click | name=file | 
    self.driver.find_element(By.NAME, "file").click()
    # 11 | type | name=file | C:\fakepath\python-3.10.7-amd64.exe
    self.driver.find_element(By.NAME, "file").send_keys("C:\\fakepath\\python-3.10.7-amd64.exe")
    # 12 | click | css=.btn-info | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-info").click()
  
