# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMenginputkontenpencarian():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_menginputkontenpencarian(self):
    # Test name: Menginput konten pencarian
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.instagram.com/")
    # 2 | setWindowSize | 656x680 | 
    self.driver.set_window_size(656, 680)
    # 3 | click | css=.x19qstwj | 
    self.driver.find_element(By.CSS_SELECTOR, ".x19qstwj").click()
    # 4 | type | css=.x1lugfcp | kemendikbud
    self.driver.find_element(By.CSS_SELECTOR, ".x1lugfcp").send_keys("kemendikbud")
    # 5 | click | css=.x1i10hfl:nth-child(3) > .x9f619 > .x9f619 > .x9f619 > .x9f619 > .x9f619 > .x9f619 > .x9f619 > .x1lliihq | 
    self.driver.find_element(By.CSS_SELECTOR, ".x1i10hfl:nth-child(3) > .x9f619 > .x9f619 > .x9f619 > .x9f619 > .x9f619 > .x9f619 > .x9f619 > .x1lliihq").click()
    # 6 | runScript | window.scrollTo(0,162) | 
    self.driver.execute_script("window.scrollTo(0,162)")
    # 7 | click | css=.\_abpo | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_abpo").click()
    # 8 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | runScript | window.scrollTo(0,283.3333435058594) | 
    self.driver.execute_script("window.scrollTo(0,283.3333435058594)")
    # 10 | mouseOver | css=.\_ac7v:nth-child(1) > .\_aabd:nth-child(3) .\_aagw | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_ac7v:nth-child(1) > .\\_aabd:nth-child(3) .\\_aagw")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | mouseOut | css=.\_ac7v:nth-child(1) > .\_aabd:nth-child(3) .\_aagw | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 12 | click | css=.\_abpo | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_abpo").click()
    # 13 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 14 | click | css=.\_aato > .\_aagw | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_aato > .\\_aagw").click()
    # 15 | click | css=.\_aaqg > .\_abl- | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_aaqg > .\\_abl-").click()
    # 16 | click | css=.\_abm1 > .x1lliihq | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_abm1 > .x1lliihq").click()
    # 17 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 18 | click | css=.x9f619:nth-child(1) > .x1i10hfl:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".x9f619:nth-child(1) > .x1i10hfl:nth-child(1)").click()
    # 19 | click | css=.x9bdzbf | 
    self.driver.find_element(By.CSS_SELECTOR, ".x9bdzbf").click()
    # 20 | runScript | window.scrollTo(0,283.3333435058594) | 
    self.driver.execute_script("window.scrollTo(0,283.3333435058594)")
    # 21 | runScript | window.scrollTo(0,163.3333282470703) | 
    self.driver.execute_script("window.scrollTo(0,163.3333282470703)")
    # 22 | click | css=.\_abpo | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_abpo").click()
    # 23 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 24 | mouseOver | css=.\_acat | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_acat")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 25 | mouseOut | css=.\_acat | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 26 | click | css=.\_aasm .x1lliihq | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_aasm .x1lliihq").click()
    # 27 | click | css=.\_a9--:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_a9--:nth-child(4)").click()
  
